workflows:
  android-workflow:
    name: ASSIST Android APK
    max_build_duration: 60
    environment:
      flutter: 3.32.2
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug --verbose
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/app-debug.apk
    publishing:
      email:
        recipients:
          - dr.arvindpotphode@gmail.com
        notify:
          success: true
          failure: true
